export { getApiClient, mockApiClient } from "./mock-client";
export type { ApiClient } from "./client";
export * as authSession from "@/lib/auth/session";
export * as settingsApi from "@/lib/api/settings";
export * as navApi from "@/lib/api/nav";
export * as footerApi from "@/lib/api/footer";
export * as footerServicesApi from "@/lib/api/footer-services";
export * as footerSocialLinksApi from "@/lib/api/footer-social-links";
export * as heroApi from "@/lib/api/hero";
export * as aboutApi from "@/lib/api/about";
export * as aspirationsApi from "@/lib/api/aspirations";
export * as projectsApi from "@/lib/api/projects";
export * as valuesApi from "@/lib/api/values";
export * as featuresApi from "@/lib/api/features";
export * as partnersApi from "@/lib/api/partners";
export * as contactApi from "@/lib/api/contact";
export * as videoApi from "@/lib/api/video";
